<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\RepoTransit.Core\RepoTransit.Core.csproj" />
    <Resource Include="Assets\RepoTransit.ico" />
    <Using Remove="System.Windows.Forms" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>Assets\RepoTransit.ico</ApplicationIcon>
  </PropertyGroup>

</Project>
